// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Pau Aliagas <linuxnow@gmail.com>
/**
 * Tests for parseXpStateInit — xp:state-init widget-option decoder.
 *
 * Exercises all three carrier formats the CMS custom-module emits:
 *   - zstd+b64:<b64>  (production default, best compression)
 *   - gzip+b64:<b64>  (fallback)
 *   - plain JSON      (debug / tiny payloads)
 *
 * Plus every failure path we promise a descriptive error for.
 */

import { describe, it, expect } from 'vitest';
import { gzipSync } from 'node:zlib';
import { spawnSync } from 'node:child_process';

import { parseXpStateInit } from './xp-state-init.js';

// fzstd (our runtime dep) ships decompress-only, so compressed test
// fixtures are generated by the `zstd` CLI that ships with glibc on
// every dev box + CI image. If zstd is unavailable we skip the
// compressed-fixture tests with a clear message rather than crashing.
function haveZstdCli() {
  const r = spawnSync('zstd', ['--version'], { encoding: 'utf-8' });
  return r.status === 0;
}

function zstdCompress(bytes) {
  const r = spawnSync('zstd', ['-q', '--no-check', '-'], { input: bytes });
  if (r.status !== 0) {
    throw new Error(`zstd CLI compression failed: ${r.stderr}`);
  }
  return new Uint8Array(r.stdout);
}

function encodeBase64(bytes) {
  return Buffer.from(bytes).toString('base64');
}

function mkGzipB64(obj) {
  const json = JSON.stringify(obj);
  const gz = gzipSync(Buffer.from(json, 'utf-8'));
  return `gzip+b64:${encodeBase64(gz)}`;
}

function mkZstdB64(obj) {
  const json = JSON.stringify(obj);
  const zstd = zstdCompress(Buffer.from(json, 'utf-8'));
  return `zstd+b64:${encodeBase64(zstd)}`;
}

const HAVE_ZSTD = haveZstdCli();
const itIfZstd = HAVE_ZSTD ? it : it.skip;

describe('parseXpStateInit — plain JSON', () => {
  it('round-trips a JSON object literal', () => {
    const src = { kioskMode: 'airport', gate: { number: 7, open: true } };
    const result = parseXpStateInit(JSON.stringify(src));
    expect(result).toEqual(src);
  });

  it('handles whitespace-padded JSON', () => {
    const result = parseXpStateInit('  \n  { "foo": 1 }\n  ');
    expect(result).toEqual({ foo: 1 });
  });
});

describe('parseXpStateInit — gzip+b64', () => {
  it('round-trips a gzip-compressed JSON payload', () => {
    const src = { a: 1, b: [1, 2, 3], c: { nested: 'yes' } };
    const encoded = mkGzipB64(src);
    expect(encoded.startsWith('gzip+b64:')).toBe(true);
    const result = parseXpStateInit(encoded);
    expect(result).toEqual(src);
  });

  it('decodes a large payload identically to the raw JSON', () => {
    // 200 keys, enough to be worth compressing.
    const src = {};
    for (let i = 0; i < 200; i++) src[`k${i}`] = { n: i, s: `value-${i}` };
    const result = parseXpStateInit(mkGzipB64(src));
    expect(result).toEqual(src);
  });
});

describe('parseXpStateInit — zstd+b64', () => {
  itIfZstd('round-trips a zstd-compressed JSON payload', () => {
    const src = { kioskMode: 'airport', lang: 'en', flags: { cta: true } };
    const encoded = mkZstdB64(src);
    expect(encoded.startsWith('zstd+b64:')).toBe(true);
    const result = parseXpStateInit(encoded);
    expect(result).toEqual(src);
  });

  itIfZstd('decodes a compressed-down-to-small payload', () => {
    const src = { repeated: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' };
    const encoded = mkZstdB64(src);
    // Zstd compresses a run of identical chars to a handful of bytes
    // so the whole "zstd+b64:" payload must be shorter than the raw
    // JSON it represents.
    expect(encoded.length).toBeLessThan(JSON.stringify(src).length);
    const result = parseXpStateInit(encoded);
    expect(result).toEqual(src);
  });
});

describe('parseXpStateInit — error paths', () => {
  it('throws on empty string', () => {
    expect(() => parseXpStateInit('')).toThrow(/empty value/);
  });

  it('throws on whitespace-only string', () => {
    expect(() => parseXpStateInit('   \n  ')).toThrow(/empty value/);
  });

  it('throws on null', () => {
    expect(() => parseXpStateInit(null)).toThrow(/empty value/);
  });

  it('throws on non-string input', () => {
    expect(() => parseXpStateInit(42)).toThrow(/expected string/);
    expect(() => parseXpStateInit({})).toThrow(/expected string/);
  });

  it('throws on an unknown compression prefix', () => {
    expect(() => parseXpStateInit('brotli+b64:SGVsbG8=')).toThrow(
      /unsupported prefix "brotli\+b64"/
    );
  });

  it('throws when the value is neither a prefix nor JSON', () => {
    expect(() => parseXpStateInit('hello-world')).toThrow(
      /neither a known compression prefix .* nor a JSON/
    );
  });

  it('throws descriptively on malformed JSON', () => {
    expect(() => parseXpStateInit('{ not: "json" }')).toThrow(
      /invalid JSON payload/
    );
  });

  it('throws on empty base64 after a valid prefix', () => {
    expect(() => parseXpStateInit('gzip+b64:')).toThrow(
      /empty base64 payload/
    );
    expect(() => parseXpStateInit('zstd+b64:')).toThrow(
      /empty base64 payload/
    );
  });

  it('throws when the decoded JSON is not an object', () => {
    // `null`, number, and array are all rejected — only {…} seeds
    // an XpStateStore cleanly.
    const b64 = (s) => `gzip+b64:${encodeBase64(gzipSync(Buffer.from(s, 'utf-8')))}`;
    expect(() => parseXpStateInit(b64('null'))).toThrow(
      /must be a JSON object/
    );
    expect(() => parseXpStateInit(b64('42'))).toThrow(/must be a JSON object/);
    expect(() => parseXpStateInit(b64('[1,2,3]'))).toThrow(
      /must be a JSON object \(got array\)/
    );
    // Top-level JSON array literal, plain JSON path.
    expect(() => parseXpStateInit('[1,2,3]')).toThrow(
      /must be a JSON object \(got array\)/
    );
  });

  it('throws when zstd payload is corrupt', () => {
    // Valid base64 of random bytes — not a real zstd frame.
    const garbage = encodeBase64(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]));
    expect(() => parseXpStateInit(`zstd+b64:${garbage}`)).toThrow(
      /zstd decompression failed/
    );
  });

  it('throws when gzip payload is corrupt', () => {
    const garbage = encodeBase64(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]));
    expect(() => parseXpStateInit(`gzip+b64:${garbage}`)).toThrow(
      /gzip decompression failed/
    );
  });

  it('throws on invalid base64 after a valid prefix', () => {
    // Characters outside the base64 alphabet (when strict) — Node's
    // Buffer is lenient, so we catch this via the downstream decode
    // path instead. The point of the test is: something bad happens
    // and we surface a useful error rather than crashing opaquely.
    expect(() => parseXpStateInit('zstd+b64:@@@not-base64@@@')).toThrow(
      /parseXpStateInit:/
    );
  });
});

describe('parseXpStateInit — payload shapes', () => {
  itIfZstd('preserves nested structures byte-identically across all three carriers', () => {
    const src = {
      kioskMode: 'airport',
      lang: 'en',
      gate: { number: 7, open: true, status: null },
      tags: ['promo', 'wayfinding'],
      metric: { nestedDeeper: { finally: 42 } }
    };

    const plain = parseXpStateInit(JSON.stringify(src));
    const gz = parseXpStateInit(mkGzipB64(src));
    const zs = parseXpStateInit(mkZstdB64(src));

    expect(plain).toEqual(src);
    expect(gz).toEqual(src);
    expect(zs).toEqual(src);
  });

  it('returns a new object (no aliasing of decoder internals)', () => {
    const src = { foo: 'bar' };
    const a = parseXpStateInit(JSON.stringify(src));
    const b = parseXpStateInit(JSON.stringify(src));
    expect(a).not.toBe(b);
    expect(a).toEqual(b);
  });
});
